uuid implementation
493-Capstone/Smartpad-macOS pull request #33
Opened 2022-04-04 12:09 UTC by DJMaest

2022-04-04 12:12 UTC, DJMaest commented
Not sure why build is failing. Passing locally.

2022-04-04 17:12 UTC, huddy987 requested changes

2022-04-04 19:34 UTC, DJMaest commented on Smartpad-macOS/Smartpad-macOS/Controller/DeviceListViewController.swift
> +              cell.textField?.stringValue = device!.displayName.components(separatedBy: "|")[0]
The reason was this is less error prone and preserves most of the current implementation. Context fields only show on invitation and discoveryInfo are only passed during the discovery callback (Which made the handling more involved). The context and discoveryInfos also won't really handle the malicious actor scenario so made this solution the way to go to make the devices uniquely identifiable. I'll look into restricting the input fields.

2022-04-04 19:35 UTC, huddy987 commented on Smartpad-macOS/Smartpad-macOS/Controller/DeviceListViewController.swift
> +              cell.textField?.stringValue = device!.displayName.components(separatedBy: "|")[0]
ok just restrict the fields then, that's good enough

2022-04-05 00:16 UTC, huddy987 approved these changes

2022-04-05 00:16 UTC, merged